packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
allowBuilds:
  canvas: set this to true or false
  core-js: set this to true or false
  cypress: set this to true or false
  electron-winstaller: set this to true or false
  esbuild: set this to true or false
