import type { GenerationParamOption } from "@/domains/generation/api/generation";

export const defaultMiniMaxVoiceId = "Chinese (Mandarin)_Warm_Bestie";

export const minimaxSystemVoiceOptions: GenerationParamOption[] = [
	{ label: "中文 (普通话) · 青涩青年音色", value: "male-qn-qingse" },
	{ label: "中文 (普通话) · 精英青年音色", value: "male-qn-jingying" },
	{ label: "中文 (普通话) · 霸道青年音色", value: "male-qn-badao" },
	{ label: "中文 (普通话) · 青年大学生音色", value: "male-qn-daxuesheng" },
	{ label: "中文 (普通话) · 少女音色", value: "female-shaonv" },
	{ label: "中文 (普通话) · 御姐音色", value: "female-yujie" },
	{ label: "中文 (普通话) · 成熟女性音色", value: "female-chengshu" },
	{ label: "中文 (普通话) · 甜美女性音色", value: "female-tianmei" },
	{ label: "中文 (普通话) · 青涩青年音色-beta", value: "male-qn-qingse-jingpin" },
	{ label: "中文 (普通话) · 精英青年音色-beta", value: "male-qn-jingying-jingpin" },
	{ label: "中文 (普通话) · 霸道青年音色-beta", value: "male-qn-badao-jingpin" },
	{ label: "中文 (普通话) · 青年大学生音色-beta", value: "male-qn-daxuesheng-jingpin" },
	{ label: "中文 (普通话) · 少女音色-beta", value: "female-shaonv-jingpin" },
	{ label: "中文 (普通话) · 御姐音色-beta", value: "female-yujie-jingpin" },
	{ label: "中文 (普通话) · 成熟女性音色-beta", value: "female-chengshu-jingpin" },
	{ label: "中文 (普通话) · 甜美女性音色-beta", value: "female-tianmei-jingpin" },
	{ label: "中文 (普通话) · 聪明男童", value: "clever_boy" },
	{ label: "中文 (普通话) · 可爱男童", value: "cute_boy" },
	{ label: "中文 (普通话) · 萌萌女童", value: "lovely_girl" },
	{ label: "中文 (普通话) · 卡通猪小琪", value: "cartoon_pig" },
	{ label: "中文 (普通话) · 病娇弟弟", value: "bingjiao_didi" },
	{ label: "中文 (普通话) · 俊朗男友", value: "junlang_nanyou" },
	{ label: "中文 (普通话) · 纯真学弟", value: "chunzhen_xuedi" },
	{ label: "中文 (普通话) · 冷淡学长", value: "lengdan_xiongzhang" },
	{ label: "中文 (普通话) · 霸道少爷", value: "badao_shaoye" },
	{ label: "中文 (普通话) · 甜心小玲", value: "tianxin_xiaoling" },
	{ label: "中文 (普通话) · 俏皮萌妹", value: "qiaopi_mengmei" },
	{ label: "中文 (普通话) · 妩媚御姐", value: "wumei_yujie" },
	{ label: "中文 (普通话) · 嗲嗲学妹", value: "diadia_xuemei" },
	{ label: "中文 (普通话) · 淡雅学姐", value: "danya_xuejie" },
	{ label: "中文 (普通话) · 沉稳高管", value: "Chinese (Mandarin)_Reliable_Executive" },
	{ label: "中文 (普通话) · 新闻女声", value: "Chinese (Mandarin)_News_Anchor" },
	{ label: "中文 (普通话) · 傲娇御姐", value: "Chinese (Mandarin)_Mature_Woman" },
	{ label: "中文 (普通话) · 不羁青年", value: "Chinese (Mandarin)_Unrestrained_Young_Man" },
	{ label: "中文 (普通话) · 嚣张小姐", value: "Arrogant_Miss" },
	{ label: "中文 (普通话) · 机械战甲", value: "Robot_Armor" },
	{ label: "中文 (普通话) · 热心大婶", value: "Chinese (Mandarin)_Kind-hearted_Antie" },
	{ label: "中文 (普通话) · 港普空姐", value: "Chinese (Mandarin)_HK_Flight_Attendant" },
	{ label: "中文 (普通话) · 搞笑大爷", value: "Chinese (Mandarin)_Humorous_Elder" },
	{ label: "中文 (普通话) · 温润男声", value: "Chinese (Mandarin)_Gentleman" },
	{ label: "中文 (普通话) · 温暖闺蜜", value: "Chinese (Mandarin)_Warm_Bestie" },
	{ label: "中文 (普通话) · 播报男声", value: "Chinese (Mandarin)_Male_Announcer" },
	{ label: "中文 (普通话) · 甜美女声", value: "Chinese (Mandarin)_Sweet_Lady" },
	{ label: "中文 (普通话) · 南方小哥", value: "Chinese (Mandarin)_Southern_Young_Man" },
	{ label: "中文 (普通话) · 阅历姐姐", value: "Chinese (Mandarin)_Wise_Women" },
	{ label: "中文 (普通话) · 温润青年", value: "Chinese (Mandarin)_Gentle_Youth" },
	{ label: "中文 (普通话) · 温暖少女", value: "Chinese (Mandarin)_Warm_Girl" },
	{ label: "中文 (普通话) · 花甲奶奶", value: "Chinese (Mandarin)_Kind-hearted_Elder" },
	{ label: "中文 (普通话) · 憨憨萌兽", value: "Chinese (Mandarin)_Cute_Spirit" },
	{ label: "中文 (普通话) · 电台男主播", value: "Chinese (Mandarin)_Radio_Host" },
	{ label: "中文 (普通话) · 抒情男声", value: "Chinese (Mandarin)_Lyrical_Voice" },
	{ label: "中文 (普通话) · 率真弟弟", value: "Chinese (Mandarin)_Straightforward_Boy" },
	{ label: "中文 (普通话) · 真诚青年", value: "Chinese (Mandarin)_Sincere_Adult" },
	{ label: "中文 (普通话) · 温柔学姐", value: "Chinese (Mandarin)_Gentle_Senior" },
	{ label: "中文 (普通话) · 嘴硬竹马", value: "Chinese (Mandarin)_Stubborn_Friend" },
	{ label: "中文 (普通话) · 清脆少女", value: "Chinese (Mandarin)_Crisp_Girl" },
	{ label: "中文 (普通话) · 清澈邻家弟弟", value: "Chinese (Mandarin)_Pure-hearted_Boy" },
	{ label: "中文 (普通话) · 柔和少女", value: "Chinese (Mandarin)_Soft_Girl" },
	{ label: "中文 (粤语) · 专业女主持", value: "Cantonese_ProfessionalHost（F)" },
	{ label: "中文 (粤语) · 温柔女声", value: "Cantonese_GentleLady" },
	{ label: "中文 (粤语) · 专业男主持", value: "Cantonese_ProfessionalHost（M)" },
	{ label: "中文 (粤语) · 活泼男声", value: "Cantonese_PlayfulMan" },
	{ label: "中文 (粤语) · 可爱女孩", value: "Cantonese_CuteGirl" },
	{ label: "中文 (粤语) · 善良女声", value: "Cantonese_KindWoman" },
	{ label: "英文 · Santa Claus", value: "Santa_Claus" },
	{ label: "英文 · Grinch", value: "Grinch" },
	{ label: "英文 · Rudolph", value: "Rudolph" },
	{ label: "英文 · Arnold", value: "Arnold" },
	{ label: "英文 · Charming Santa", value: "Charming_Santa" },
	{ label: "英文 · Charming Lady", value: "Charming_Lady" },
	{ label: "英文 · Sweet Girl", value: "Sweet_Girl" },
	{ label: "英文 · Cute Elf", value: "Cute_Elf" },
	{ label: "英文 · Attractive Girl", value: "Attractive_Girl" },
	{ label: "英文 · Serene Woman", value: "Serene_Woman" },
	{ label: "英文 · Trustworthy Man", value: "English_Trustworthy_Man" },
	{ label: "英文 · Graceful Lady", value: "English_Graceful_Lady" },
	{ label: "英文 · Aussie Bloke", value: "English_Aussie_Bloke" },
	{ label: "英文 · Whispering girl", value: "English_Whispering_girl" },
	{ label: "英文 · Diligent Man", value: "English_Diligent_Man" },
	{ label: "英文 · Gentle-voiced man", value: "English_Gentle-voiced_man" },
	{ label: "日文 · Intellectual Senior", value: "Japanese_IntellectualSenior" },
	{ label: "日文 · Decisive Princess", value: "Japanese_DecisivePrincess" },
	{ label: "日文 · Loyal Knight", value: "Japanese_LoyalKnight" },
	{ label: "日文 · Dominant Man", value: "Japanese_DominantMan" },
	{ label: "日文 · Serious Commander", value: "Japanese_SeriousCommander" },
	{ label: "日文 · Cold Queen", value: "Japanese_ColdQueen" },
	{ label: "日文 · Dependable Woman", value: "Japanese_DependableWoman" },
	{ label: "日文 · Gentle Butler", value: "Japanese_GentleButler" },
	{ label: "日文 · Kind Lady", value: "Japanese_KindLady" },
	{ label: "日文 · Calm Lady", value: "Japanese_CalmLady" },
	{ label: "日文 · Optimistic Youth", value: "Japanese_OptimisticYouth" },
	{ label: "日文 · Generous Izakaya Owner", value: "Japanese_GenerousIzakayaOwner" },
	{ label: "日文 · Sporty Student", value: "Japanese_SportyStudent" },
	{ label: "日文 · Innocent Boy", value: "Japanese_InnocentBoy" },
	{ label: "日文 · Graceful Maiden", value: "Japanese_GracefulMaiden" },
	{ label: "韩文 · Sweet Girl", value: "Korean_SweetGirl" },
	{ label: "韩文 · Cheerful Boyfriend", value: "Korean_CheerfulBoyfriend" },
	{ label: "韩文 · Enchanting Sister", value: "Korean_EnchantingSister" },
	{ label: "韩文 · Shy Girl", value: "Korean_ShyGirl" },
	{ label: "韩文 · Reliable Sister", value: "Korean_ReliableSister" },
	{ label: "韩文 · Strict Boss", value: "Korean_StrictBoss" },
	{ label: "韩文 · Sassy Girl", value: "Korean_SassyGirl" },
	{ label: "韩文 · Childhood Friend Girl", value: "Korean_ChildhoodFriendGirl" },
	{ label: "韩文 · Playboy Charmer", value: "Korean_PlayboyCharmer" },
	{ label: "韩文 · Elegant Princess", value: "Korean_ElegantPrincess" },
	{ label: "韩文 · Brave Female Warrior", value: "Korean_BraveFemaleWarrior" },
	{ label: "韩文 · Brave Youth", value: "Korean_BraveYouth" },
	{ label: "韩文 · Calm Lady", value: "Korean_CalmLady" },
	{ label: "韩文 · Enthusiastic Teen", value: "Korean_EnthusiasticTeen" },
	{ label: "韩文 · Soothing Lady", value: "Korean_SoothingLady" },
	{ label: "韩文 · Intellectual Senior", value: "Korean_IntellectualSenior" },
	{ label: "韩文 · Lonely Warrior", value: "Korean_LonelyWarrior" },
	{ label: "韩文 · Mature Lady", value: "Korean_MatureLady" },
	{ label: "韩文 · Innocent Boy", value: "Korean_InnocentBoy" },
	{ label: "韩文 · Charming Sister", value: "Korean_CharmingSister" },
	{ label: "韩文 · Athletic Student", value: "Korean_AthleticStudent" },
	{ label: "韩文 · Brave Adventurer", value: "Korean_BraveAdventurer" },
	{ label: "韩文 · Calm Gentleman", value: "Korean_CalmGentleman" },
	{ label: "韩文 · Wise Elf", value: "Korean_WiseElf" },
	{ label: "韩文 · Cheerful Cool Junior", value: "Korean_CheerfulCoolJunior" },
	{ label: "韩文 · Decisive Queen", value: "Korean_DecisiveQueen" },
	{ label: "韩文 · Cold Young Man", value: "Korean_ColdYoungMan" },
	{ label: "韩文 · Mysterious Girl", value: "Korean_MysteriousGirl" },
	{ label: "韩文 · Quirky Girl", value: "Korean_QuirkyGirl" },
	{ label: "韩文 · Considerate Senior", value: "Korean_ConsiderateSenior" },
	{ label: "韩文 · Cheerful Little Sister", value: "Korean_CheerfulLittleSister" },
	{ label: "韩文 · Dominant Man", value: "Korean_DominantMan" },
	{ label: "韩文 · Airheaded Girl", value: "Korean_AirheadedGirl" },
	{ label: "韩文 · Reliable Youth", value: "Korean_ReliableYouth" },
	{ label: "韩文 · Friendly Big Sister", value: "Korean_FriendlyBigSister" },
	{ label: "韩文 · Gentle Boss", value: "Korean_GentleBoss" },
	{ label: "韩文 · Cold Girl", value: "Korean_ColdGirl" },
	{ label: "韩文 · Haughty Lady", value: "Korean_HaughtyLady" },
	{ label: "韩文 · Charming Elder Sister", value: "Korean_CharmingElderSister" },
	{ label: "韩文 · Intellectual Man", value: "Korean_IntellectualMan" },
	{ label: "韩文 · Caring Woman", value: "Korean_CaringWoman" },
	{ label: "韩文 · Wise Teacher", value: "Korean_WiseTeacher" },
	{ label: "韩文 · Confident Boss", value: "Korean_ConfidentBoss" },
	{ label: "韩文 · Athletic Girl", value: "Korean_AthleticGirl" },
	{ label: "韩文 · Possessive Man", value: "Korean_PossessiveMan" },
	{ label: "韩文 · Gentle Woman", value: "Korean_GentleWoman" },
	{ label: "韩文 · Cocky Guy", value: "Korean_CockyGuy" },
	{ label: "韩文 · Thoughtful Woman", value: "Korean_ThoughtfulWoman" },
	{ label: "韩文 · Optimistic Youth", value: "Korean_OptimisticYouth" },
	{ label: "西班牙文 · Serene Woman", value: "Spanish_SereneWoman" },
	{ label: "西班牙文 · Mature Partner", value: "Spanish_MaturePartner" },
	{ label: "西班牙文 · Captivating Storyteller", value: "Spanish_CaptivatingStoryteller" },
	{ label: "西班牙文 · Narrator", value: "Spanish_Narrator" },
	{ label: "西班牙文 · Wise Scholar", value: "Spanish_WiseScholar" },
	{ label: "西班牙文 · Kind-hearted Girl", value: "Spanish_Kind-heartedGirl" },
	{ label: "西班牙文 · Determined Manager", value: "Spanish_DeterminedManager" },
	{ label: "西班牙文 · Bossy Leader", value: "Spanish_BossyLeader" },
	{ label: "西班牙文 · Reserved Young Man", value: "Spanish_ReservedYoungMan" },
	{ label: "西班牙文 · Confident Woman", value: "Spanish_ConfidentWoman" },
	{ label: "西班牙文 · Thoughtful Man", value: "Spanish_ThoughtfulMan" },
	{ label: "西班牙文 · Strong-willed Boy", value: "Spanish_Strong-WilledBoy" },
	{ label: "西班牙文 · Sophisticated Lady", value: "Spanish_SophisticatedLady" },
	{ label: "西班牙文 · Rational Man", value: "Spanish_RationalMan" },
	{ label: "西班牙文 · Anime Character", value: "Spanish_AnimeCharacter" },
	{ label: "西班牙文 · Deep-toned Man", value: "Spanish_Deep-tonedMan" },
	{ label: "西班牙文 · Fussy hostess", value: "Spanish_Fussyhostess" },
	{ label: "西班牙文 · Sincere Teen", value: "Spanish_SincereTeen" },
	{ label: "西班牙文 · Frank Lady", value: "Spanish_FrankLady" },
	{ label: "西班牙文 · Comedian", value: "Spanish_Comedian" },
	{ label: "西班牙文 · Debator", value: "Spanish_Debator" },
	{ label: "西班牙文 · Tough Boss", value: "Spanish_ToughBoss" },
	{ label: "西班牙文 · Wise Lady", value: "Spanish_Wiselady" },
	{ label: "西班牙文 · Steady Mentor", value: "Spanish_Steadymentor" },
	{ label: "西班牙文 · Jovial Man", value: "Spanish_Jovialman" },
	{ label: "西班牙文 · Santa Claus", value: "Spanish_SantaClaus" },
	{ label: "西班牙文 · Rudolph", value: "Spanish_Rudolph" },
	{ label: "西班牙文 · Intonate Girl", value: "Spanish_Intonategirl" },
	{ label: "西班牙文 · Arnold", value: "Spanish_Arnold" },
	{ label: "西班牙文 · Ghost", value: "Spanish_Ghost" },
	{ label: "西班牙文 · Humorous Elder", value: "Spanish_HumorousElder" },
	{ label: "西班牙文 · Energetic Boy", value: "Spanish_EnergeticBoy" },
	{ label: "西班牙文 · Whimsical Girl", value: "Spanish_WhimsicalGirl" },
	{ label: "西班牙文 · Strict Boss", value: "Spanish_StrictBoss" },
	{ label: "西班牙文 · Reliable Man", value: "Spanish_ReliableMan" },
	{ label: "西班牙文 · Serene Elder", value: "Spanish_SereneElder" },
	{ label: "西班牙文 · Angry Man", value: "Spanish_AngryMan" },
	{ label: "西班牙文 · Assertive Queen", value: "Spanish_AssertiveQueen" },
	{ label: "西班牙文 · Caring Girlfriend", value: "Spanish_CaringGirlfriend" },
	{ label: "西班牙文 · Powerful Soldier", value: "Spanish_PowerfulSoldier" },
	{ label: "西班牙文 · Passionate Warrior", value: "Spanish_PassionateWarrior" },
	{ label: "西班牙文 · Chatty Girl", value: "Spanish_ChattyGirl" },
	{ label: "西班牙文 · Romantic Husband", value: "Spanish_RomanticHusband" },
	{ label: "西班牙文 · Compelling Girl", value: "Spanish_CompellingGirl" },
	{ label: "西班牙文 · Powerful Veteran", value: "Spanish_PowerfulVeteran" },
	{ label: "西班牙文 · Sensible Manager", value: "Spanish_SensibleManager" },
	{ label: "西班牙文 · Thoughtful Lady", value: "Spanish_ThoughtfulLady" },
	{ label: "葡萄牙文 · Sentimental Lady", value: "Portuguese_SentimentalLady" },
	{ label: "葡萄牙文 · Bossy Leader", value: "Portuguese_BossyLeader" },
	{ label: "葡萄牙文 · Wise lady", value: "Portuguese_Wiselady" },
	{ label: "葡萄牙文 · Strong-willed Boy", value: "Portuguese_Strong-WilledBoy" },
	{ label: "葡萄牙文 · Deep-voiced Gentleman", value: "Portuguese_Deep-VoicedGentleman" },
	{ label: "葡萄牙文 · Upset Girl", value: "Portuguese_UpsetGirl" },
	{ label: "葡萄牙文 · Passionate Warrior", value: "Portuguese_PassionateWarrior" },
	{ label: "葡萄牙文 · Anime Character", value: "Portuguese_AnimeCharacter" },
	{ label: "葡萄牙文 · Confident Woman", value: "Portuguese_ConfidentWoman" },
	{ label: "葡萄牙文 · Angry Man", value: "Portuguese_AngryMan" },
	{ label: "葡萄牙文 · Captivating Storyteller", value: "Portuguese_CaptivatingStoryteller" },
	{ label: "葡萄牙文 · Godfather", value: "Portuguese_Godfather" },
	{ label: "葡萄牙文 · Reserved Young Man", value: "Portuguese_ReservedYoungMan" },
	{ label: "葡萄牙文 · Smart Young Girl", value: "Portuguese_SmartYoungGirl" },
	{ label: "葡萄牙文 · Kind-hearted Girl", value: "Portuguese_Kind-heartedGirl" },
	{ label: "葡萄牙文 · Pompous lady", value: "Portuguese_Pompouslady" },
	{ label: "葡萄牙文 · Grinch", value: "Portuguese_Grinch" },
	{ label: "葡萄牙文 · Debator", value: "Portuguese_Debator" },
	{ label: "葡萄牙文 · Sweet Girl", value: "Portuguese_SweetGirl" },
	{ label: "葡萄牙文 · Attractive Girl", value: "Portuguese_AttractiveGirl" },
	{ label: "葡萄牙文 · Thoughtful Man", value: "Portuguese_ThoughtfulMan" },
	{ label: "葡萄牙文 · Playful Girl", value: "Portuguese_PlayfulGirl" },
	{ label: "葡萄牙文 · Gorgeous Lady", value: "Portuguese_GorgeousLady" },
	{ label: "葡萄牙文 · Lovely Lady", value: "Portuguese_LovelyLady" },
	{ label: "葡萄牙文 · Serene Woman", value: "Portuguese_SereneWoman" },
	{ label: "葡萄牙文 · Sad Teen", value: "Portuguese_SadTeen" },
	{ label: "葡萄牙文 · Mature Partner", value: "Portuguese_MaturePartner" },
	{ label: "葡萄牙文 · Comedian", value: "Portuguese_Comedian" },
	{ label: "葡萄牙文 · Naughty Schoolgirl", value: "Portuguese_NaughtySchoolgirl" },
	{ label: "葡萄牙文 · Narrator", value: "Portuguese_Narrator" },
	{ label: "葡萄牙文 · Tough Boss", value: "Portuguese_ToughBoss" },
	{ label: "葡萄牙文 · Fussy hostess", value: "Portuguese_Fussyhostess" },
	{ label: "葡萄牙文 · Dramatist", value: "Portuguese_Dramatist" },
	{ label: "葡萄牙文 · Steady Mentor", value: "Portuguese_Steadymentor" },
	{ label: "葡萄牙文 · Jovial Man", value: "Portuguese_Jovialman" },
	{ label: "葡萄牙文 · Charming Queen", value: "Portuguese_CharmingQueen" },
	{ label: "葡萄牙文 · Santa Claus", value: "Portuguese_SantaClaus" },
	{ label: "葡萄牙文 · Rudolph", value: "Portuguese_Rudolph" },
	{ label: "葡萄牙文 · Arnold", value: "Portuguese_Arnold" },
	{ label: "葡萄牙文 · Charming Santa", value: "Portuguese_CharmingSanta" },
	{ label: "葡萄牙文 · Charming Lady", value: "Portuguese_CharmingLady" },
	{ label: "葡萄牙文 · Ghost", value: "Portuguese_Ghost" },
	{ label: "葡萄牙文 · Humorous Elder", value: "Portuguese_HumorousElder" },
	{ label: "葡萄牙文 · Calm Leader", value: "Portuguese_CalmLeader" },
	{ label: "葡萄牙文 · Gentle Teacher", value: "Portuguese_GentleTeacher" },
	{ label: "葡萄牙文 · Energetic Boy", value: "Portuguese_EnergeticBoy" },
	{ label: "葡萄牙文 · Reliable Man", value: "Portuguese_ReliableMan" },
	{ label: "葡萄牙文 · Serene Elder", value: "Portuguese_SereneElder" },
	{ label: "葡萄牙文 · Grim Reaper", value: "Portuguese_GrimReaper" },
	{ label: "葡萄牙文 · Assertive Queen", value: "Portuguese_AssertiveQueen" },
	{ label: "葡萄牙文 · Whimsical Girl", value: "Portuguese_WhimsicalGirl" },
	{ label: "葡萄牙文 · Stressed Lady", value: "Portuguese_StressedLady" },
	{ label: "葡萄牙文 · Friendly Neighbor", value: "Portuguese_FriendlyNeighbor" },
	{ label: "葡萄牙文 · Caring Girlfriend", value: "Portuguese_CaringGirlfriend" },
	{ label: "葡萄牙文 · Powerful Soldier", value: "Portuguese_PowerfulSoldier" },
	{ label: "葡萄牙文 · Fascinating Boy", value: "Portuguese_FascinatingBoy" },
	{ label: "葡萄牙文 · Romantic Husband", value: "Portuguese_RomanticHusband" },
	{ label: "葡萄牙文 · Strict Boss", value: "Portuguese_StrictBoss" },
	{ label: "葡萄牙文 · Inspiring Lady", value: "Portuguese_InspiringLady" },
	{ label: "葡萄牙文 · Playful Spirit", value: "Portuguese_PlayfulSpirit" },
	{ label: "葡萄牙文 · Elegant Girl", value: "Portuguese_ElegantGirl" },
	{ label: "葡萄牙文 · Compelling Girl", value: "Portuguese_CompellingGirl" },
	{ label: "葡萄牙文 · Powerful Veteran", value: "Portuguese_PowerfulVeteran" },
	{ label: "葡萄牙文 · Sensible Manager", value: "Portuguese_SensibleManager" },
	{ label: "葡萄牙文 · Thoughtful Lady", value: "Portuguese_ThoughtfulLady" },
	{ label: "葡萄牙文 · Theatrical Actor", value: "Portuguese_TheatricalActor" },
	{ label: "葡萄牙文 · Fragile Boy", value: "Portuguese_FragileBoy" },
	{ label: "葡萄牙文 · Chatty Girl", value: "Portuguese_ChattyGirl" },
	{ label: "葡萄牙文 · Conscientious Instructor", value: "Portuguese_Conscientiousinstructor" },
	{ label: "葡萄牙文 · Rational Man", value: "Portuguese_RationalMan" },
	{ label: "葡萄牙文 · Wise Scholar", value: "Portuguese_WiseScholar" },
	{ label: "葡萄牙文 · Frank Lady", value: "Portuguese_FrankLady" },
	{ label: "葡萄牙文 · Determined Manager", value: "Portuguese_DeterminedManager" },
	{ label: "法文 · Level-Headed Man", value: "French_Male_Speech_New" },
	{ label: "法文 · Patient Female Presenter", value: "French_Female_News Anchor" },
	{ label: "法文 · Casual Man", value: "French_CasualMan" },
	{ label: "法文 · Movie Lead Female", value: "French_MovieLeadFemale" },
	{ label: "法文 · Female Anchor", value: "French_FemaleAnchor" },
	{ label: "法文 · Male Narrator", value: "French_MaleNarrator" },
	{ label: "印尼文 · Sweet Girl", value: "Indonesian_SweetGirl" },
	{ label: "印尼文 · Reserved Young Man", value: "Indonesian_ReservedYoungMan" },
	{ label: "印尼文 · Charming Girl", value: "Indonesian_CharmingGirl" },
	{ label: "印尼文 · Calm Woman", value: "Indonesian_CalmWoman" },
	{ label: "印尼文 · Confident Woman", value: "Indonesian_ConfidentWoman" },
	{ label: "印尼文 · Caring Man", value: "Indonesian_CaringMan" },
	{ label: "印尼文 · Bossy Leader", value: "Indonesian_BossyLeader" },
	{ label: "印尼文 · Determined Boy", value: "Indonesian_DeterminedBoy" },
	{ label: "印尼文 · Gentle Girl", value: "Indonesian_GentleGirl" },
	{ label: "德文 · Friendly Man", value: "German_FriendlyMan" },
	{ label: "德文 · Sweet Lady", value: "German_SweetLady" },
	{ label: "德文 · Playful Man", value: "German_PlayfulMan" },
	{ label: "俄文 · Handsome Childhood Friend", value: "Russian_HandsomeChildhoodFriend" },
	{ label: "俄文 · Bright Queen", value: "Russian_BrightHeroine" },
	{ label: "俄文 · Ambitious Woman", value: "Russian_AmbitiousWoman" },
	{ label: "俄文 · Reliable Man", value: "Russian_ReliableMan" },
	{ label: "俄文 · Crazy Girl", value: "Russian_CrazyQueen" },
	{ label: "俄文 · Pessimistic Girl", value: "Russian_PessimisticGirl" },
	{ label: "俄文 · Attractive Guy", value: "Russian_AttractiveGuy" },
	{ label: "俄文 · Bad-tempered Boy", value: "Russian_Bad-temperedBoy" },
	{ label: "意大利文 · Brave Heroine", value: "Italian_BraveHeroine" },
	{ label: "意大利文 · Narrator", value: "Italian_Narrator" },
	{ label: "意大利文 · Wandering Sorcerer", value: "Italian_WanderingSorcerer" },
	{ label: "意大利文 · Diligent Leader", value: "Italian_DiligentLeader" },
	{ label: "阿拉伯文 · Calm Woman", value: "Arabic_CalmWoman" },
	{ label: "阿拉伯文 · Friendly Guy", value: "Arabic_FriendlyGuy" },
	{ label: "土耳其文 · Calm Woman", value: "Turkish_CalmWoman" },
	{ label: "土耳其文 · Trustworthy man", value: "Turkish_Trustworthyman" },
	{ label: "乌克兰文 · Calm Woman", value: "Ukrainian_CalmWoman" },
	{ label: "乌克兰文 · Wise Scholar", value: "Ukrainian_WiseScholar" },
	{ label: "荷兰文 · Kind-hearted girl", value: "Dutch_kindhearted_girl" },
	{ label: "荷兰文 · Bossy leader", value: "Dutch_bossy_leader" },
	{ label: "越南文 · Kind-hearted girl", value: "Vietnamese_kindhearted_girl" },
	{ label: "泰文 · Serene Man", value: "Thai_male_1_sample8" },
	{ label: "泰文 · Friendly Man", value: "Thai_male_2_sample2" },
	{ label: "泰文 · Confident Woman", value: "Thai_female_1_sample1" },
	{ label: "泰文 · Energetic Woman", value: "Thai_female_2_sample2" },
	{ label: "波兰文 · Male Narrator", value: "Polish_male_1_sample4" },
	{ label: "波兰文 · Male Anchor", value: "Polish_male_2_sample3" },
	{ label: "波兰文 · Calm Woman", value: "Polish_female_1_sample1" },
	{ label: "波兰文 · Casual Woman", value: "Polish_female_2_sample3" },
	{ label: "罗马尼亚文 · Reliable Man", value: "Romanian_male_1_sample2" },
	{ label: "罗马尼亚文 · Energetic Youth", value: "Romanian_male_2_sample1" },
	{ label: "罗马尼亚文 · Optimistic Youth", value: "Romanian_female_1_sample4" },
	{ label: "罗马尼亚文 · Gentle Woman", value: "Romanian_female_2_sample1" },
	{ label: "希腊文 · Thoughtful Mentor", value: "greek_male_1a_v1" },
	{ label: "希腊文 · Gentle Lady", value: "Greek_female_1_sample1" },
	{ label: "希腊文 · Girl Next Door", value: "Greek_female_2_sample3" },
	{ label: "捷克文 · Assured Presenter", value: "czech_male_1_v1" },
	{ label: "捷克文 · Steadfast Narrator", value: "czech_female_5_v7" },
	{ label: "捷克文 · Elegant Lady", value: "czech_female_2_v2" },
	{ label: "芬兰文 · Upbeat Man", value: "finnish_male_3_v1" },
	{ label: "芬兰文 · Friendly Boy", value: "finnish_male_1_v2" },
	{ label: "芬兰文 · Assetive Woman", value: "finnish_female_4_v1" },
	{ label: "印地文 · Trustworthy Advisor", value: "hindi_male_1_v2" },
	{ label: "印地文 · Tranquil Woman", value: "hindi_female_2_v1" },
	{ label: "印地文 · News Anchor", value: "hindi_female_1_v2" },
];
