package generation

const (
	FamilySeedream      = "seedream"
	FamilyMiniMaxSpeech = "minimax-speech"
	FamilyGPTText       = "gpt-text"
	FamilyGeminiText    = "gemini-text"
	FamilyMiniMaxText   = "minimax-text"
	FamilyDeepSeekText  = "deepseek-text"
	FamilyGPTImage      = "gpt-image"
	FamilyNanoBanana    = "nano-banana"
	FamilySeedance      = "seedance"

	VersionSeedream5Lite           = "seedream-5-lite"
	VersionSeedream47              = "seedream-4.7"
	VersionMiniMaxSpeech28HD       = "minimax-speech-2.8-hd"
	VersionMiniMaxSpeech28Turbo    = "minimax-speech-2.8-turbo"
	VersionGPT41MiniText           = "gpt-4.1-mini-text"
	VersionGPT5MiniText            = "gpt-5-mini-text"
	VersionGPT55Text               = "gpt-5.5-text"
	VersionGPT54Text               = "gpt-5.4-text"
	VersionGPT54MiniText           = "gpt-5.4-mini-text"
	VersionGemini35FlashText       = "gemini-3.5-flash-text"
	VersionGemini31ProText         = "gemini-3.1-pro-preview-text"
	VersionGemini31FlashLiteText   = "gemini-3.1-flash-lite-text"
	VersionMiniMaxM3Text           = "minimax-m3-text"
	VersionMiniMaxM27Text          = "minimax-m2.7-text"
	VersionMiniMaxM27HighspeedText = "minimax-m2.7-highspeed-text"
	VersionDeepSeekV4FlashText     = "deepseek-v4-flash-text"
	VersionDeepSeekV4ProText       = "deepseek-v4-pro-text"
	VersionSeedream45              = "seedream-4.5"
	VersionGPTImage2               = "gpt-image-2"
	VersionGPT54Image2             = "gpt-5.4-image-2"
	VersionNanoBanana31            = "gemini-3.1-flash-image-preview"
	VersionNanoBananaPro           = "gemini-3-pro-image-preview"
	VersionNanoBanana25            = "gemini-2.5-flash-image"
	VersionSeedance20Fast          = "seedance-2.0-fast"
	VersionSeedance20Mini          = "seedance-2.0-mini"
	VersionSeedance20              = "seedance-2.0"
	VersionSeedance20FastVIP       = "seedance-2.0-fast-vip"
	VersionSeedance20VIP           = "seedance-2.0-vip"
	VersionSeedance15Pro           = "seedance-1.5-pro"

	ModelSeedream5Lite           = "seedream-5-lite"
	ModelSeedream50              = "seedream-5.0"
	ModelSeedream47              = "seedream-4.7"
	ModelMiniMaxSpeech28HD       = "minimax-speech-2.8-hd"
	ModelMiniMaxSpeech28Turbo    = "minimax-speech-2.8-turbo"
	ModelGPT41MiniText           = "gpt-4.1-mini-text"
	ModelGPT5MiniText            = "gpt-5-mini-text"
	ModelGPT55Text               = "gpt-5.5-text"
	ModelGPT54Text               = "gpt-5.4-text"
	ModelGPT54MiniText           = "gpt-5.4-mini-text"
	ModelGemini35FlashText       = "gemini-3.5-flash-text"
	ModelGemini31ProText         = "gemini-3.1-pro-preview-text"
	ModelGemini31FlashLiteText   = "gemini-3.1-flash-lite-text"
	ModelMiniMaxM3Text           = "minimax-m3-text"
	ModelMiniMaxM27Text          = "minimax-m2.7-text"
	ModelMiniMaxM27HighspeedText = "minimax-m2.7-highspeed-text"
	ModelDeepSeekV4FlashText     = "deepseek-v4-flash-text"
	ModelDeepSeekV4ProText       = "deepseek-v4-pro-text"
	ModelGPTImage2               = "gpt-image-2"
	ModelNanoBanana              = "nano-banana"
	ModelJimengSeedance2Fast     = "jimeng-seedance-2-fast"
)
