package generation

const (
	RouteDMXSeedream5Lite                = "dmx.seedream-5-lite"
	RouteOfficialMiniMaxSpeech28HD       = "official.minimax-speech-2.8-hd"
	RouteOfficialMiniMaxSpeech28Turbo    = "official.minimax-speech-2.8-turbo"
	RouteDMXGPT41MiniText                = "dmx.gpt-4.1-mini-text"
	RouteDMXGPTImage2                    = "dmx.gpt-image-2"
	RouteDMXNanoBanana31                 = "dmx.gemini-3.1-flash-image-preview"
	RouteDMXSeedance20Fast               = "dmx.seedance-2.0-fast"
	RouteJimengSeedream50                = "jimeng.seedream-5.0"
	RouteJimengSeedream47                = "jimeng.seedream-4.7"
	RouteJimengSeedance20Fast            = "jimeng.seedance-2.0-fast"
	RouteJimengSeedance20Mini            = "jimeng.seedance-2.0-mini"
	RouteJimengSeedance20                = "jimeng.seedance-2.0"
	RouteJimengSeedance20FastVIP         = "jimeng.seedance-2.0-fast-vip"
	RouteJimengSeedance20VIP             = "jimeng.seedance-2.0-vip"
	RouteOpenRouterSeedream45            = "openrouter.seedream-4.5"
	RouteOpenRouterGPT41MiniText         = "openrouter.gpt-4.1-mini-text"
	RouteOpenRouterGPT5MiniText          = "openrouter.gpt-5-mini-text"
	RouteOpenRouterGPT54Image2           = "openrouter.gpt-5.4-image-2"
	RouteOpenRouterNanoBanana31          = "openrouter.gemini-3.1-flash-image-preview"
	RouteOpenRouterNanoBananaPro         = "openrouter.gemini-3-pro-image-preview"
	RouteOpenRouterNanoBanana25          = "openrouter.gemini-2.5-flash-image"
	RouteOpenRouterSeedance20Fast        = "openrouter.seedance-2.0-fast"
	RouteOpenRouterSeedance20            = "openrouter.seedance-2.0"
	RouteOpenRouterSeedance15Pro         = "openrouter.seedance-1.5-pro"
	RouteOfficialSeedream5Lite           = "official.seedream-5-lite"
	RouteOfficialGPT41MiniText           = "official.gpt-4.1-mini-text"
	RouteOfficialGPT5MiniText            = "official.gpt-5-mini-text"
	RouteOfficialGPT55Text               = "official.gpt-5.5-text"
	RouteOfficialGPT54Text               = "official.gpt-5.4-text"
	RouteOfficialGPT54MiniText           = "official.gpt-5.4-mini-text"
	RouteOfficialGemini35FlashText       = "official.gemini-3.5-flash-text"
	RouteOfficialGemini31ProText         = "official.gemini-3.1-pro-preview-text"
	RouteOfficialGemini31FlashLiteText   = "official.gemini-3.1-flash-lite-text"
	RouteOfficialMiniMaxM3Text           = "official.minimax-m3-text"
	RouteOfficialMiniMaxM27Text          = "official.minimax-m2.7-text"
	RouteOfficialMiniMaxM27HighspeedText = "official.minimax-m2.7-highspeed-text"
	RouteOfficialDeepSeekV4FlashText     = "official.deepseek-v4-flash-text"
	RouteOfficialDeepSeekV4ProText       = "official.deepseek-v4-pro-text"
	RouteOfficialGPTImage2               = "official.gpt-image-2"
	RouteOfficialNanoBanana31            = "official.gemini-3.1-flash-image-preview"
	RouteOfficialSeedance20Fast          = "official.seedance-2.0-fast"
)
