package generation

const (
	ProviderOpenAI     = "openai"
	ProviderGoogle     = "google"
	ProviderMiniMax    = "minimax"
	ProviderDeepSeek   = "deepseek"
	ProviderVolcengine = "volcengine"
	ProviderAliyun     = "aliyun"
	ProviderMediago    = "mediago"
	ProviderDMX        = "dmx"
	ProviderOpenRouter = "openrouter"
	ProviderJimeng     = "jimeng"
	ProviderLibTV      = "libtv"
	ProviderXiaoyunque = "xiaoyunque"

	AdapterOfficialPlanned               = "official.planned"
	AdapterOfficialOpenAIImage           = "official.openai.image"
	AdapterOfficialOpenAIChatText        = "official.openai.chat_text"
	AdapterOfficialGoogleImage           = "official.google.image"
	AdapterOfficialGoogleChatText        = "official.google.chat_text"
	AdapterOfficialMiniMaxChatText       = "official.minimax.chat_text"
	AdapterOfficialMiniMaxSpeech         = "official.minimax.speech"
	AdapterOfficialDeepSeekChatText      = "official.deepseek.chat_text"
	AdapterOfficialVolcengineImage       = "official.volcengine.image"
	AdapterOfficialVolcengineVideo       = "official.volcengine.video"
	AdapterOfficialAliyunWanImage        = "official.aliyun.wan_image"
	AdapterOfficialAliyunHappyHorseVideo = "official.aliyun.happyhorse_video"
	AdapterOpenRouterImages              = "openrouter.images"
	AdapterOpenRouterChatImage           = "openrouter.chat.image"
	AdapterOpenRouterChatText            = "openrouter.chat.text"
	AdapterOpenRouterVideo               = "openrouter.video"
	AdapterMediagoChatImage              = "mediago.chat.image"
	AdapterMediagoImages                 = "mediago.images"
	AdapterMediagoText                   = "mediago.text"
	AdapterMediagoVideo                  = "mediago.video"
	AdapterDMXChatText                   = "dmx.chat.text"
	AdapterDMXResponsesImage             = "dmx.responses.image"
	AdapterDMXImagesGenerations          = "dmx.images.generations"
	AdapterDMXGeminiGenerate             = "dmx.gemini.generate_content"
	AdapterDMXResponsesVideo             = "dmx.responses.video"
	AdapterJimengCLIImage                = "jimeng.cli.image"
	AdapterJimengCLIVideo                = "jimeng.cli.video"
	AdapterLibTVCLIImage                 = "libtv.cli.image"
	AdapterLibTVCLIVideo                 = "libtv.cli.video"
	AdapterPippitCLIVideo                = "pippit.cli.video"
)
