package generation

const defaultMiniMaxVoiceID = "Chinese (Mandarin)_Warm_Bestie"

func minimaxSystemVoiceOptions() []ParamOption {
	return []ParamOption{
		{Label: "中文 (普通话) · 青涩青年音色", Value: "male-qn-qingse"},
		{Label: "中文 (普通话) · 精英青年音色", Value: "male-qn-jingying"},
		{Label: "中文 (普通话) · 霸道青年音色", Value: "male-qn-badao"},
		{Label: "中文 (普通话) · 青年大学生音色", Value: "male-qn-daxuesheng"},
		{Label: "中文 (普通话) · 少女音色", Value: "female-shaonv"},
		{Label: "中文 (普通话) · 御姐音色", Value: "female-yujie"},
		{Label: "中文 (普通话) · 成熟女性音色", Value: "female-chengshu"},
		{Label: "中文 (普通话) · 甜美女性音色", Value: "female-tianmei"},
		{Label: "中文 (普通话) · 青涩青年音色-beta", Value: "male-qn-qingse-jingpin"},
		{Label: "中文 (普通话) · 精英青年音色-beta", Value: "male-qn-jingying-jingpin"},
		{Label: "中文 (普通话) · 霸道青年音色-beta", Value: "male-qn-badao-jingpin"},
		{Label: "中文 (普通话) · 青年大学生音色-beta", Value: "male-qn-daxuesheng-jingpin"},
		{Label: "中文 (普通话) · 少女音色-beta", Value: "female-shaonv-jingpin"},
		{Label: "中文 (普通话) · 御姐音色-beta", Value: "female-yujie-jingpin"},
		{Label: "中文 (普通话) · 成熟女性音色-beta", Value: "female-chengshu-jingpin"},
		{Label: "中文 (普通话) · 甜美女性音色-beta", Value: "female-tianmei-jingpin"},
		{Label: "中文 (普通话) · 聪明男童", Value: "clever_boy"},
		{Label: "中文 (普通话) · 可爱男童", Value: "cute_boy"},
		{Label: "中文 (普通话) · 萌萌女童", Value: "lovely_girl"},
		{Label: "中文 (普通话) · 卡通猪小琪", Value: "cartoon_pig"},
		{Label: "中文 (普通话) · 病娇弟弟", Value: "bingjiao_didi"},
		{Label: "中文 (普通话) · 俊朗男友", Value: "junlang_nanyou"},
		{Label: "中文 (普通话) · 纯真学弟", Value: "chunzhen_xuedi"},
		{Label: "中文 (普通话) · 冷淡学长", Value: "lengdan_xiongzhang"},
		{Label: "中文 (普通话) · 霸道少爷", Value: "badao_shaoye"},
		{Label: "中文 (普通话) · 甜心小玲", Value: "tianxin_xiaoling"},
		{Label: "中文 (普通话) · 俏皮萌妹", Value: "qiaopi_mengmei"},
		{Label: "中文 (普通话) · 妩媚御姐", Value: "wumei_yujie"},
		{Label: "中文 (普通话) · 嗲嗲学妹", Value: "diadia_xuemei"},
		{Label: "中文 (普通话) · 淡雅学姐", Value: "danya_xuejie"},
		{Label: "中文 (普通话) · 沉稳高管", Value: "Chinese (Mandarin)_Reliable_Executive"},
		{Label: "中文 (普通话) · 新闻女声", Value: "Chinese (Mandarin)_News_Anchor"},
		{Label: "中文 (普通话) · 傲娇御姐", Value: "Chinese (Mandarin)_Mature_Woman"},
		{Label: "中文 (普通话) · 不羁青年", Value: "Chinese (Mandarin)_Unrestrained_Young_Man"},
		{Label: "中文 (普通话) · 嚣张小姐", Value: "Arrogant_Miss"},
		{Label: "中文 (普通话) · 机械战甲", Value: "Robot_Armor"},
		{Label: "中文 (普通话) · 热心大婶", Value: "Chinese (Mandarin)_Kind-hearted_Antie"},
		{Label: "中文 (普通话) · 港普空姐", Value: "Chinese (Mandarin)_HK_Flight_Attendant"},
		{Label: "中文 (普通话) · 搞笑大爷", Value: "Chinese (Mandarin)_Humorous_Elder"},
		{Label: "中文 (普通话) · 温润男声", Value: "Chinese (Mandarin)_Gentleman"},
		{Label: "中文 (普通话) · 温暖闺蜜", Value: "Chinese (Mandarin)_Warm_Bestie"},
		{Label: "中文 (普通话) · 播报男声", Value: "Chinese (Mandarin)_Male_Announcer"},
		{Label: "中文 (普通话) · 甜美女声", Value: "Chinese (Mandarin)_Sweet_Lady"},
		{Label: "中文 (普通话) · 南方小哥", Value: "Chinese (Mandarin)_Southern_Young_Man"},
		{Label: "中文 (普通话) · 阅历姐姐", Value: "Chinese (Mandarin)_Wise_Women"},
		{Label: "中文 (普通话) · 温润青年", Value: "Chinese (Mandarin)_Gentle_Youth"},
		{Label: "中文 (普通话) · 温暖少女", Value: "Chinese (Mandarin)_Warm_Girl"},
		{Label: "中文 (普通话) · 花甲奶奶", Value: "Chinese (Mandarin)_Kind-hearted_Elder"},
		{Label: "中文 (普通话) · 憨憨萌兽", Value: "Chinese (Mandarin)_Cute_Spirit"},
		{Label: "中文 (普通话) · 电台男主播", Value: "Chinese (Mandarin)_Radio_Host"},
		{Label: "中文 (普通话) · 抒情男声", Value: "Chinese (Mandarin)_Lyrical_Voice"},
		{Label: "中文 (普通话) · 率真弟弟", Value: "Chinese (Mandarin)_Straightforward_Boy"},
		{Label: "中文 (普通话) · 真诚青年", Value: "Chinese (Mandarin)_Sincere_Adult"},
		{Label: "中文 (普通话) · 温柔学姐", Value: "Chinese (Mandarin)_Gentle_Senior"},
		{Label: "中文 (普通话) · 嘴硬竹马", Value: "Chinese (Mandarin)_Stubborn_Friend"},
		{Label: "中文 (普通话) · 清脆少女", Value: "Chinese (Mandarin)_Crisp_Girl"},
		{Label: "中文 (普通话) · 清澈邻家弟弟", Value: "Chinese (Mandarin)_Pure-hearted_Boy"},
		{Label: "中文 (普通话) · 柔和少女", Value: "Chinese (Mandarin)_Soft_Girl"},
		{Label: "中文 (粤语) · 专业女主持", Value: "Cantonese_ProfessionalHost（F)"},
		{Label: "中文 (粤语) · 温柔女声", Value: "Cantonese_GentleLady"},
		{Label: "中文 (粤语) · 专业男主持", Value: "Cantonese_ProfessionalHost（M)"},
		{Label: "中文 (粤语) · 活泼男声", Value: "Cantonese_PlayfulMan"},
		{Label: "中文 (粤语) · 可爱女孩", Value: "Cantonese_CuteGirl"},
		{Label: "中文 (粤语) · 善良女声", Value: "Cantonese_KindWoman"},
		{Label: "英文 · Santa Claus", Value: "Santa_Claus"},
		{Label: "英文 · Grinch", Value: "Grinch"},
		{Label: "英文 · Rudolph", Value: "Rudolph"},
		{Label: "英文 · Arnold", Value: "Arnold"},
		{Label: "英文 · Charming Santa", Value: "Charming_Santa"},
		{Label: "英文 · Charming Lady", Value: "Charming_Lady"},
		{Label: "英文 · Sweet Girl", Value: "Sweet_Girl"},
		{Label: "英文 · Cute Elf", Value: "Cute_Elf"},
		{Label: "英文 · Attractive Girl", Value: "Attractive_Girl"},
		{Label: "英文 · Serene Woman", Value: "Serene_Woman"},
		{Label: "英文 · Trustworthy Man", Value: "English_Trustworthy_Man"},
		{Label: "英文 · Graceful Lady", Value: "English_Graceful_Lady"},
		{Label: "英文 · Aussie Bloke", Value: "English_Aussie_Bloke"},
		{Label: "英文 · Whispering girl", Value: "English_Whispering_girl"},
		{Label: "英文 · Diligent Man", Value: "English_Diligent_Man"},
		{Label: "英文 · Gentle-voiced man", Value: "English_Gentle-voiced_man"},
		{Label: "日文 · Intellectual Senior", Value: "Japanese_IntellectualSenior"},
		{Label: "日文 · Decisive Princess", Value: "Japanese_DecisivePrincess"},
		{Label: "日文 · Loyal Knight", Value: "Japanese_LoyalKnight"},
		{Label: "日文 · Dominant Man", Value: "Japanese_DominantMan"},
		{Label: "日文 · Serious Commander", Value: "Japanese_SeriousCommander"},
		{Label: "日文 · Cold Queen", Value: "Japanese_ColdQueen"},
		{Label: "日文 · Dependable Woman", Value: "Japanese_DependableWoman"},
		{Label: "日文 · Gentle Butler", Value: "Japanese_GentleButler"},
		{Label: "日文 · Kind Lady", Value: "Japanese_KindLady"},
		{Label: "日文 · Calm Lady", Value: "Japanese_CalmLady"},
		{Label: "日文 · Optimistic Youth", Value: "Japanese_OptimisticYouth"},
		{Label: "日文 · Generous Izakaya Owner", Value: "Japanese_GenerousIzakayaOwner"},
		{Label: "日文 · Sporty Student", Value: "Japanese_SportyStudent"},
		{Label: "日文 · Innocent Boy", Value: "Japanese_InnocentBoy"},
		{Label: "日文 · Graceful Maiden", Value: "Japanese_GracefulMaiden"},
		{Label: "韩文 · Sweet Girl", Value: "Korean_SweetGirl"},
		{Label: "韩文 · Cheerful Boyfriend", Value: "Korean_CheerfulBoyfriend"},
		{Label: "韩文 · Enchanting Sister", Value: "Korean_EnchantingSister"},
		{Label: "韩文 · Shy Girl", Value: "Korean_ShyGirl"},
		{Label: "韩文 · Reliable Sister", Value: "Korean_ReliableSister"},
		{Label: "韩文 · Strict Boss", Value: "Korean_StrictBoss"},
		{Label: "韩文 · Sassy Girl", Value: "Korean_SassyGirl"},
		{Label: "韩文 · Childhood Friend Girl", Value: "Korean_ChildhoodFriendGirl"},
		{Label: "韩文 · Playboy Charmer", Value: "Korean_PlayboyCharmer"},
		{Label: "韩文 · Elegant Princess", Value: "Korean_ElegantPrincess"},
		{Label: "韩文 · Brave Female Warrior", Value: "Korean_BraveFemaleWarrior"},
		{Label: "韩文 · Brave Youth", Value: "Korean_BraveYouth"},
		{Label: "韩文 · Calm Lady", Value: "Korean_CalmLady"},
		{Label: "韩文 · Enthusiastic Teen", Value: "Korean_EnthusiasticTeen"},
		{Label: "韩文 · Soothing Lady", Value: "Korean_SoothingLady"},
		{Label: "韩文 · Intellectual Senior", Value: "Korean_IntellectualSenior"},
		{Label: "韩文 · Lonely Warrior", Value: "Korean_LonelyWarrior"},
		{Label: "韩文 · Mature Lady", Value: "Korean_MatureLady"},
		{Label: "韩文 · Innocent Boy", Value: "Korean_InnocentBoy"},
		{Label: "韩文 · Charming Sister", Value: "Korean_CharmingSister"},
		{Label: "韩文 · Athletic Student", Value: "Korean_AthleticStudent"},
		{Label: "韩文 · Brave Adventurer", Value: "Korean_BraveAdventurer"},
		{Label: "韩文 · Calm Gentleman", Value: "Korean_CalmGentleman"},
		{Label: "韩文 · Wise Elf", Value: "Korean_WiseElf"},
		{Label: "韩文 · Cheerful Cool Junior", Value: "Korean_CheerfulCoolJunior"},
		{Label: "韩文 · Decisive Queen", Value: "Korean_DecisiveQueen"},
		{Label: "韩文 · Cold Young Man", Value: "Korean_ColdYoungMan"},
		{Label: "韩文 · Mysterious Girl", Value: "Korean_MysteriousGirl"},
		{Label: "韩文 · Quirky Girl", Value: "Korean_QuirkyGirl"},
		{Label: "韩文 · Considerate Senior", Value: "Korean_ConsiderateSenior"},
		{Label: "韩文 · Cheerful Little Sister", Value: "Korean_CheerfulLittleSister"},
		{Label: "韩文 · Dominant Man", Value: "Korean_DominantMan"},
		{Label: "韩文 · Airheaded Girl", Value: "Korean_AirheadedGirl"},
		{Label: "韩文 · Reliable Youth", Value: "Korean_ReliableYouth"},
		{Label: "韩文 · Friendly Big Sister", Value: "Korean_FriendlyBigSister"},
		{Label: "韩文 · Gentle Boss", Value: "Korean_GentleBoss"},
		{Label: "韩文 · Cold Girl", Value: "Korean_ColdGirl"},
		{Label: "韩文 · Haughty Lady", Value: "Korean_HaughtyLady"},
		{Label: "韩文 · Charming Elder Sister", Value: "Korean_CharmingElderSister"},
		{Label: "韩文 · Intellectual Man", Value: "Korean_IntellectualMan"},
		{Label: "韩文 · Caring Woman", Value: "Korean_CaringWoman"},
		{Label: "韩文 · Wise Teacher", Value: "Korean_WiseTeacher"},
		{Label: "韩文 · Confident Boss", Value: "Korean_ConfidentBoss"},
		{Label: "韩文 · Athletic Girl", Value: "Korean_AthleticGirl"},
		{Label: "韩文 · Possessive Man", Value: "Korean_PossessiveMan"},
		{Label: "韩文 · Gentle Woman", Value: "Korean_GentleWoman"},
		{Label: "韩文 · Cocky Guy", Value: "Korean_CockyGuy"},
		{Label: "韩文 · Thoughtful Woman", Value: "Korean_ThoughtfulWoman"},
		{Label: "韩文 · Optimistic Youth", Value: "Korean_OptimisticYouth"},
		{Label: "西班牙文 · Serene Woman", Value: "Spanish_SereneWoman"},
		{Label: "西班牙文 · Mature Partner", Value: "Spanish_MaturePartner"},
		{Label: "西班牙文 · Captivating Storyteller", Value: "Spanish_CaptivatingStoryteller"},
		{Label: "西班牙文 · Narrator", Value: "Spanish_Narrator"},
		{Label: "西班牙文 · Wise Scholar", Value: "Spanish_WiseScholar"},
		{Label: "西班牙文 · Kind-hearted Girl", Value: "Spanish_Kind-heartedGirl"},
		{Label: "西班牙文 · Determined Manager", Value: "Spanish_DeterminedManager"},
		{Label: "西班牙文 · Bossy Leader", Value: "Spanish_BossyLeader"},
		{Label: "西班牙文 · Reserved Young Man", Value: "Spanish_ReservedYoungMan"},
		{Label: "西班牙文 · Confident Woman", Value: "Spanish_ConfidentWoman"},
		{Label: "西班牙文 · Thoughtful Man", Value: "Spanish_ThoughtfulMan"},
		{Label: "西班牙文 · Strong-willed Boy", Value: "Spanish_Strong-WilledBoy"},
		{Label: "西班牙文 · Sophisticated Lady", Value: "Spanish_SophisticatedLady"},
		{Label: "西班牙文 · Rational Man", Value: "Spanish_RationalMan"},
		{Label: "西班牙文 · Anime Character", Value: "Spanish_AnimeCharacter"},
		{Label: "西班牙文 · Deep-toned Man", Value: "Spanish_Deep-tonedMan"},
		{Label: "西班牙文 · Fussy hostess", Value: "Spanish_Fussyhostess"},
		{Label: "西班牙文 · Sincere Teen", Value: "Spanish_SincereTeen"},
		{Label: "西班牙文 · Frank Lady", Value: "Spanish_FrankLady"},
		{Label: "西班牙文 · Comedian", Value: "Spanish_Comedian"},
		{Label: "西班牙文 · Debator", Value: "Spanish_Debator"},
		{Label: "西班牙文 · Tough Boss", Value: "Spanish_ToughBoss"},
		{Label: "西班牙文 · Wise Lady", Value: "Spanish_Wiselady"},
		{Label: "西班牙文 · Steady Mentor", Value: "Spanish_Steadymentor"},
		{Label: "西班牙文 · Jovial Man", Value: "Spanish_Jovialman"},
		{Label: "西班牙文 · Santa Claus", Value: "Spanish_SantaClaus"},
		{Label: "西班牙文 · Rudolph", Value: "Spanish_Rudolph"},
		{Label: "西班牙文 · Intonate Girl", Value: "Spanish_Intonategirl"},
		{Label: "西班牙文 · Arnold", Value: "Spanish_Arnold"},
		{Label: "西班牙文 · Ghost", Value: "Spanish_Ghost"},
		{Label: "西班牙文 · Humorous Elder", Value: "Spanish_HumorousElder"},
		{Label: "西班牙文 · Energetic Boy", Value: "Spanish_EnergeticBoy"},
		{Label: "西班牙文 · Whimsical Girl", Value: "Spanish_WhimsicalGirl"},
		{Label: "西班牙文 · Strict Boss", Value: "Spanish_StrictBoss"},
		{Label: "西班牙文 · Reliable Man", Value: "Spanish_ReliableMan"},
		{Label: "西班牙文 · Serene Elder", Value: "Spanish_SereneElder"},
		{Label: "西班牙文 · Angry Man", Value: "Spanish_AngryMan"},
		{Label: "西班牙文 · Assertive Queen", Value: "Spanish_AssertiveQueen"},
		{Label: "西班牙文 · Caring Girlfriend", Value: "Spanish_CaringGirlfriend"},
		{Label: "西班牙文 · Powerful Soldier", Value: "Spanish_PowerfulSoldier"},
		{Label: "西班牙文 · Passionate Warrior", Value: "Spanish_PassionateWarrior"},
		{Label: "西班牙文 · Chatty Girl", Value: "Spanish_ChattyGirl"},
		{Label: "西班牙文 · Romantic Husband", Value: "Spanish_RomanticHusband"},
		{Label: "西班牙文 · Compelling Girl", Value: "Spanish_CompellingGirl"},
		{Label: "西班牙文 · Powerful Veteran", Value: "Spanish_PowerfulVeteran"},
		{Label: "西班牙文 · Sensible Manager", Value: "Spanish_SensibleManager"},
		{Label: "西班牙文 · Thoughtful Lady", Value: "Spanish_ThoughtfulLady"},
		{Label: "葡萄牙文 · Sentimental Lady", Value: "Portuguese_SentimentalLady"},
		{Label: "葡萄牙文 · Bossy Leader", Value: "Portuguese_BossyLeader"},
		{Label: "葡萄牙文 · Wise lady", Value: "Portuguese_Wiselady"},
		{Label: "葡萄牙文 · Strong-willed Boy", Value: "Portuguese_Strong-WilledBoy"},
		{Label: "葡萄牙文 · Deep-voiced Gentleman", Value: "Portuguese_Deep-VoicedGentleman"},
		{Label: "葡萄牙文 · Upset Girl", Value: "Portuguese_UpsetGirl"},
		{Label: "葡萄牙文 · Passionate Warrior", Value: "Portuguese_PassionateWarrior"},
		{Label: "葡萄牙文 · Anime Character", Value: "Portuguese_AnimeCharacter"},
		{Label: "葡萄牙文 · Confident Woman", Value: "Portuguese_ConfidentWoman"},
		{Label: "葡萄牙文 · Angry Man", Value: "Portuguese_AngryMan"},
		{Label: "葡萄牙文 · Captivating Storyteller", Value: "Portuguese_CaptivatingStoryteller"},
		{Label: "葡萄牙文 · Godfather", Value: "Portuguese_Godfather"},
		{Label: "葡萄牙文 · Reserved Young Man", Value: "Portuguese_ReservedYoungMan"},
		{Label: "葡萄牙文 · Smart Young Girl", Value: "Portuguese_SmartYoungGirl"},
		{Label: "葡萄牙文 · Kind-hearted Girl", Value: "Portuguese_Kind-heartedGirl"},
		{Label: "葡萄牙文 · Pompous lady", Value: "Portuguese_Pompouslady"},
		{Label: "葡萄牙文 · Grinch", Value: "Portuguese_Grinch"},
		{Label: "葡萄牙文 · Debator", Value: "Portuguese_Debator"},
		{Label: "葡萄牙文 · Sweet Girl", Value: "Portuguese_SweetGirl"},
		{Label: "葡萄牙文 · Attractive Girl", Value: "Portuguese_AttractiveGirl"},
		{Label: "葡萄牙文 · Thoughtful Man", Value: "Portuguese_ThoughtfulMan"},
		{Label: "葡萄牙文 · Playful Girl", Value: "Portuguese_PlayfulGirl"},
		{Label: "葡萄牙文 · Gorgeous Lady", Value: "Portuguese_GorgeousLady"},
		{Label: "葡萄牙文 · Lovely Lady", Value: "Portuguese_LovelyLady"},
		{Label: "葡萄牙文 · Serene Woman", Value: "Portuguese_SereneWoman"},
		{Label: "葡萄牙文 · Sad Teen", Value: "Portuguese_SadTeen"},
		{Label: "葡萄牙文 · Mature Partner", Value: "Portuguese_MaturePartner"},
		{Label: "葡萄牙文 · Comedian", Value: "Portuguese_Comedian"},
		{Label: "葡萄牙文 · Naughty Schoolgirl", Value: "Portuguese_NaughtySchoolgirl"},
		{Label: "葡萄牙文 · Narrator", Value: "Portuguese_Narrator"},
		{Label: "葡萄牙文 · Tough Boss", Value: "Portuguese_ToughBoss"},
		{Label: "葡萄牙文 · Fussy hostess", Value: "Portuguese_Fussyhostess"},
		{Label: "葡萄牙文 · Dramatist", Value: "Portuguese_Dramatist"},
		{Label: "葡萄牙文 · Steady Mentor", Value: "Portuguese_Steadymentor"},
		{Label: "葡萄牙文 · Jovial Man", Value: "Portuguese_Jovialman"},
		{Label: "葡萄牙文 · Charming Queen", Value: "Portuguese_CharmingQueen"},
		{Label: "葡萄牙文 · Santa Claus", Value: "Portuguese_SantaClaus"},
		{Label: "葡萄牙文 · Rudolph", Value: "Portuguese_Rudolph"},
		{Label: "葡萄牙文 · Arnold", Value: "Portuguese_Arnold"},
		{Label: "葡萄牙文 · Charming Santa", Value: "Portuguese_CharmingSanta"},
		{Label: "葡萄牙文 · Charming Lady", Value: "Portuguese_CharmingLady"},
		{Label: "葡萄牙文 · Ghost", Value: "Portuguese_Ghost"},
		{Label: "葡萄牙文 · Humorous Elder", Value: "Portuguese_HumorousElder"},
		{Label: "葡萄牙文 · Calm Leader", Value: "Portuguese_CalmLeader"},
		{Label: "葡萄牙文 · Gentle Teacher", Value: "Portuguese_GentleTeacher"},
		{Label: "葡萄牙文 · Energetic Boy", Value: "Portuguese_EnergeticBoy"},
		{Label: "葡萄牙文 · Reliable Man", Value: "Portuguese_ReliableMan"},
		{Label: "葡萄牙文 · Serene Elder", Value: "Portuguese_SereneElder"},
		{Label: "葡萄牙文 · Grim Reaper", Value: "Portuguese_GrimReaper"},
		{Label: "葡萄牙文 · Assertive Queen", Value: "Portuguese_AssertiveQueen"},
		{Label: "葡萄牙文 · Whimsical Girl", Value: "Portuguese_WhimsicalGirl"},
		{Label: "葡萄牙文 · Stressed Lady", Value: "Portuguese_StressedLady"},
		{Label: "葡萄牙文 · Friendly Neighbor", Value: "Portuguese_FriendlyNeighbor"},
		{Label: "葡萄牙文 · Caring Girlfriend", Value: "Portuguese_CaringGirlfriend"},
		{Label: "葡萄牙文 · Powerful Soldier", Value: "Portuguese_PowerfulSoldier"},
		{Label: "葡萄牙文 · Fascinating Boy", Value: "Portuguese_FascinatingBoy"},
		{Label: "葡萄牙文 · Romantic Husband", Value: "Portuguese_RomanticHusband"},
		{Label: "葡萄牙文 · Strict Boss", Value: "Portuguese_StrictBoss"},
		{Label: "葡萄牙文 · Inspiring Lady", Value: "Portuguese_InspiringLady"},
		{Label: "葡萄牙文 · Playful Spirit", Value: "Portuguese_PlayfulSpirit"},
		{Label: "葡萄牙文 · Elegant Girl", Value: "Portuguese_ElegantGirl"},
		{Label: "葡萄牙文 · Compelling Girl", Value: "Portuguese_CompellingGirl"},
		{Label: "葡萄牙文 · Powerful Veteran", Value: "Portuguese_PowerfulVeteran"},
		{Label: "葡萄牙文 · Sensible Manager", Value: "Portuguese_SensibleManager"},
		{Label: "葡萄牙文 · Thoughtful Lady", Value: "Portuguese_ThoughtfulLady"},
		{Label: "葡萄牙文 · Theatrical Actor", Value: "Portuguese_TheatricalActor"},
		{Label: "葡萄牙文 · Fragile Boy", Value: "Portuguese_FragileBoy"},
		{Label: "葡萄牙文 · Chatty Girl", Value: "Portuguese_ChattyGirl"},
		{Label: "葡萄牙文 · Conscientious Instructor", Value: "Portuguese_Conscientiousinstructor"},
		{Label: "葡萄牙文 · Rational Man", Value: "Portuguese_RationalMan"},
		{Label: "葡萄牙文 · Wise Scholar", Value: "Portuguese_WiseScholar"},
		{Label: "葡萄牙文 · Frank Lady", Value: "Portuguese_FrankLady"},
		{Label: "葡萄牙文 · Determined Manager", Value: "Portuguese_DeterminedManager"},
		{Label: "法文 · Level-Headed Man", Value: "French_Male_Speech_New"},
		{Label: "法文 · Patient Female Presenter", Value: "French_Female_News Anchor"},
		{Label: "法文 · Casual Man", Value: "French_CasualMan"},
		{Label: "法文 · Movie Lead Female", Value: "French_MovieLeadFemale"},
		{Label: "法文 · Female Anchor", Value: "French_FemaleAnchor"},
		{Label: "法文 · Male Narrator", Value: "French_MaleNarrator"},
		{Label: "印尼文 · Sweet Girl", Value: "Indonesian_SweetGirl"},
		{Label: "印尼文 · Reserved Young Man", Value: "Indonesian_ReservedYoungMan"},
		{Label: "印尼文 · Charming Girl", Value: "Indonesian_CharmingGirl"},
		{Label: "印尼文 · Calm Woman", Value: "Indonesian_CalmWoman"},
		{Label: "印尼文 · Confident Woman", Value: "Indonesian_ConfidentWoman"},
		{Label: "印尼文 · Caring Man", Value: "Indonesian_CaringMan"},
		{Label: "印尼文 · Bossy Leader", Value: "Indonesian_BossyLeader"},
		{Label: "印尼文 · Determined Boy", Value: "Indonesian_DeterminedBoy"},
		{Label: "印尼文 · Gentle Girl", Value: "Indonesian_GentleGirl"},
		{Label: "德文 · Friendly Man", Value: "German_FriendlyMan"},
		{Label: "德文 · Sweet Lady", Value: "German_SweetLady"},
		{Label: "德文 · Playful Man", Value: "German_PlayfulMan"},
		{Label: "俄文 · Handsome Childhood Friend", Value: "Russian_HandsomeChildhoodFriend"},
		{Label: "俄文 · Bright Queen", Value: "Russian_BrightHeroine"},
		{Label: "俄文 · Ambitious Woman", Value: "Russian_AmbitiousWoman"},
		{Label: "俄文 · Reliable Man", Value: "Russian_ReliableMan"},
		{Label: "俄文 · Crazy Girl", Value: "Russian_CrazyQueen"},
		{Label: "俄文 · Pessimistic Girl", Value: "Russian_PessimisticGirl"},
		{Label: "俄文 · Attractive Guy", Value: "Russian_AttractiveGuy"},
		{Label: "俄文 · Bad-tempered Boy", Value: "Russian_Bad-temperedBoy"},
		{Label: "意大利文 · Brave Heroine", Value: "Italian_BraveHeroine"},
		{Label: "意大利文 · Narrator", Value: "Italian_Narrator"},
		{Label: "意大利文 · Wandering Sorcerer", Value: "Italian_WanderingSorcerer"},
		{Label: "意大利文 · Diligent Leader", Value: "Italian_DiligentLeader"},
		{Label: "阿拉伯文 · Calm Woman", Value: "Arabic_CalmWoman"},
		{Label: "阿拉伯文 · Friendly Guy", Value: "Arabic_FriendlyGuy"},
		{Label: "土耳其文 · Calm Woman", Value: "Turkish_CalmWoman"},
		{Label: "土耳其文 · Trustworthy man", Value: "Turkish_Trustworthyman"},
		{Label: "乌克兰文 · Calm Woman", Value: "Ukrainian_CalmWoman"},
		{Label: "乌克兰文 · Wise Scholar", Value: "Ukrainian_WiseScholar"},
		{Label: "荷兰文 · Kind-hearted girl", Value: "Dutch_kindhearted_girl"},
		{Label: "荷兰文 · Bossy leader", Value: "Dutch_bossy_leader"},
		{Label: "越南文 · Kind-hearted girl", Value: "Vietnamese_kindhearted_girl"},
		{Label: "泰文 · Serene Man", Value: "Thai_male_1_sample8"},
		{Label: "泰文 · Friendly Man", Value: "Thai_male_2_sample2"},
		{Label: "泰文 · Confident Woman", Value: "Thai_female_1_sample1"},
		{Label: "泰文 · Energetic Woman", Value: "Thai_female_2_sample2"},
		{Label: "波兰文 · Male Narrator", Value: "Polish_male_1_sample4"},
		{Label: "波兰文 · Male Anchor", Value: "Polish_male_2_sample3"},
		{Label: "波兰文 · Calm Woman", Value: "Polish_female_1_sample1"},
		{Label: "波兰文 · Casual Woman", Value: "Polish_female_2_sample3"},
		{Label: "罗马尼亚文 · Reliable Man", Value: "Romanian_male_1_sample2"},
		{Label: "罗马尼亚文 · Energetic Youth", Value: "Romanian_male_2_sample1"},
		{Label: "罗马尼亚文 · Optimistic Youth", Value: "Romanian_female_1_sample4"},
		{Label: "罗马尼亚文 · Gentle Woman", Value: "Romanian_female_2_sample1"},
		{Label: "希腊文 · Thoughtful Mentor", Value: "greek_male_1a_v1"},
		{Label: "希腊文 · Gentle Lady", Value: "Greek_female_1_sample1"},
		{Label: "希腊文 · Girl Next Door", Value: "Greek_female_2_sample3"},
		{Label: "捷克文 · Assured Presenter", Value: "czech_male_1_v1"},
		{Label: "捷克文 · Steadfast Narrator", Value: "czech_female_5_v7"},
		{Label: "捷克文 · Elegant Lady", Value: "czech_female_2_v2"},
		{Label: "芬兰文 · Upbeat Man", Value: "finnish_male_3_v1"},
		{Label: "芬兰文 · Friendly Boy", Value: "finnish_male_1_v2"},
		{Label: "芬兰文 · Assetive Woman", Value: "finnish_female_4_v1"},
		{Label: "印地文 · Trustworthy Advisor", Value: "hindi_male_1_v2"},
		{Label: "印地文 · Tranquil Woman", Value: "hindi_female_2_v1"},
		{Label: "印地文 · News Anchor", Value: "hindi_female_1_v2"},
	}
}
